version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: canditrack-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: canditrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: